"""PDF report generation for documents."""
import io
from datetime import datetime, timezone
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak,
)
from reportlab.lib import colors

from .models import Document


async def generate_document_report(doc: Document) -> io.BytesIO:
    buf = io.BytesIO()
    doc_template = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=20,
        textColor=HexColor("#1a1a2e"),
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=HexColor("#16213e"),
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        spaceAfter=6,
    )

    elements = []

    # Title
    elements.append(Paragraph(f"Document Report: {doc.original_name}", title_style))
    elements.append(Spacer(1, 6 * mm))

    # Metadata
    meta = [
        ["Filename", doc.original_name],
        ["Type", doc.file_type.upper()],
        ["Size", f"{doc.file_size / 1024:.1f} KB"],
        ["Status", doc.status.value],
        ["Processed", doc.updated_at.strftime("%Y-%m-%d %H:%M UTC")],
    ]
    meta_table = Table(meta, colWidths=[80 * mm, 100 * mm])
    meta_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), HexColor("#e8e8e8")),
        ("TEXTCOLOR", (0, 0), (-1, -1), HexColor("#333333")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("PADDING", (0, 0), (-1, -1), 6),
    ]))
    elements.append(meta_table)
    elements.append(Spacer(1, 8 * mm))

    # OCR Text
    if doc.ocr_text:
        elements.append(Paragraph("Extracted Text (OCR)", heading_style))
        elements.append(Paragraph(doc.ocr_text[:3000], body_style))

    # AI Summary
    if doc.ai_summary:
        elements.append(Paragraph("AI Summary", heading_style))
        elements.append(Paragraph(doc.ai_summary, body_style))

    # Extracted Data
    if doc.extracted_data:
        elements.append(Paragraph("Extracted Data", heading_style))
        data_rows = [[Paragraph(str(k), body_style), Paragraph(str(v), body_style)]
                     for k, v in doc.extracted_data.items()]
        data_table = Table(
            [["Field", "Value"]] + data_rows,
            colWidths=[80 * mm, 100 * mm],
        )
        data_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), HexColor("#16213e")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 10),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("PADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(data_table)

    # Footer
    elements.append(Spacer(1, 10 * mm))
    elements.append(
        Paragraph(
            f"Generated by AI Document Processing on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            ParagraphStyle("Footer", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
        )
    )

    doc_template.build(elements)
    buf.seek(0)
    return buf
